name: CI/CD
on:
  push:
    branches: [ test_on_windows ]

jobs:
  install_and_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run make install
        run: make install

      - name: Run make build
        run: make build