name: CI/CD
on:
  push:
    branches: [ test_on_windows ]

jobs:
  install_and_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run environment var
        run: env

      - name: Run make install
        run: make install

      - name: Run print path again
        run: make -C install/windows printPath

      - name: Run make build
        run: make build

      -name: Print certs
       run: cat /etc/ssl/certs/ca-certificates.crt
